Repository voxpupuli/hiera-eyaml, pull requests merged in 2022-05, with the labels that each got.

#330 Build gem during CI
  .github/workflows/test.yml
Labels: enhancement

#326 Add more Ruby/Puppet versions to CI matrix
  .github/workflows/test.yml
  Gemfile
  features/sandbox/clean_home/.puppetlabs/opt/puppet/public/placeholder
  features/sandbox/puppet/public/.gitignore
Labels: enhancement

#329 Repair ruby 3.1.x compability with backwards compability. Bumped vers…
  lib/hiera/backend/eyaml/plugins.rb
Labels: bug

#328 Release 3.3.0
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Gemfile
  README.md
  Rakefile
  hiera-eyaml.gemspec
  lib/hiera/backend/eyaml.rb
Labels: skip-changelog
