Repository voxpupuli/hiera-eyaml, pull requests merged in 2024-05, with the labels that each got.

#366 Drop support for ruby 2.6
  hiera-eyaml.gemspec
Labels: backwards-incompatible

#370 rubocop: lint for Ruby 2.7
  .rubocop.yml
  .rubocop_todo.yml
  Rakefile
  features/step_definitions/environment_overrides.rb
  features/step_definitions/parser_steps.rb
  features/step_definitions/recrypt_steps.rb
  features/support/env.rb
  lib/hiera/backend/eyaml/encryptors/pkcs7.rb
  lib/hiera/backend/eyaml/logginghelper.rb
  lib/hiera/backend/eyaml/subcommand.rb
Labels: enhancement

#374 CI: fix coverage reporting
  .github/workflows/test.yml
Labels: bug

#376 Add more jruby interpreter to CI
  .github/workflows/test.yml
Labels: enhancement

#379 Add support to encrypt with an RSA public key
  lib/hiera/backend/eyaml/encryptors/pkcs7.rb
Labels: enhancement

#380 Remove non-essential public certificate attributes
  lib/hiera/backend/eyaml/encryptors/pkcs7.rb
Labels: enhancement

#381 Release 4.0.0
  CHANGELOG.md
  Rakefile
  lib/hiera/backend/eyaml.rb
Labels: skip-changelog

#378 Remove public key requirement to decrypt
  README.md
  lib/hiera/backend/eyaml/encryptors/pkcs7.rb
Labels: enhancement

#382 Release 4.1.0
  CHANGELOG.md
  lib/hiera/backend/eyaml.rb
Labels: skip-changelog
